title: Little taskless ponies
baseURL: https://pedantic-thompson-8e824a.netlify.com
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Moje. Zmizte.
  authors: elf

